### PR TITLE
Don't build twice in pull requests

### PR DESCRIPTION
**Pull request by probonopd**
type2-runtime is already doing it like this.

### CODE REVIEW

**Comment by TheAssassin** [comment]
This could be called "force user to create PR to get builds". I'm not really a fan of this. In what way is this needed? We have enough free runner slots so this won't save build time.

**Comment by probonopd** [comment]
It saves a lot of energy and hence presumably CO2.

**Comment by TheAssassin** [comment]
> It saves a lot of energy and hence presumably CO2.

It _can_. But detecting problems early can save more of this. This is a straw man fallacy IMO. I'm not aware of any studies.

**Comment by probonopd** [comment]
I'd still be in favor of this. Its also cleaner and simpler visually in the PRs.

**Comment by probonopd** [comment]
https://github.com/AppImage/type2-runtime/pull/28 is the opposite of this, so maybe we should not merge this PR?

**Comment by TheAssassin** [comment]
`pull_request` tests a potential merge conflict. `push` builds the branch as it would build `main`. Both serve separate purposes. Especially when working with CI changes, `push` is absolutely needed to be able to evaluate what is going on. I don't think it makes a lot of sense to add extra work and make a temporary commit every time one needs to test such a change like done recently while working on the type 2 runtime. Closing therefore.

**Comment by TheAssassin** [comment]
What a coincidence. Yes, I think this should be closed.

**Pull request closed without merging**
