### PR TITLE
Chroot build

### PR DESCRIPTION
**Pull request by Randrianasulu**
Draft/for review scripts allowing new makeimagetool to be build in chroot, copied with some mods from type2-runtime scripts

### CODE REVIEW

**Comment by TheAssassin** [comment]
No idea what you want to achieve. No intention to maintain such a build script at all.

**Comment by Randrianasulu** [comment]
> No idea what you want to achieve.

Another part of appkit was buildable with chroot, without Docker Docker requres Go, and Go rebuilds are slow - I installed it all in the end and it even worked, but I prefer to not have additional dependencies if possible.

**Comment by probonopd** [comment]
So you would like to build `appimagetool` without Docker, is that what you would like to achieve?

**Comment by TheAssassin** [comment]
That is entirely possible. I do not intend to maintain any secondary build systems, no way. type2-runtime is the only exception.

**Comment by Randrianasulu** [comment]
> So you would like to build `appimagetool` without Docker, is that what you would like to achieve?

yes.

but because @TheAssassin do not want it in mainline - fine, its still out there, so at least if I or anyone else will need this in the future there is starting point at least.

**Comment by probonopd** [comment]
Thanks @Randrianasulu. I can understand you not wanting to use Docker, but I can also understand @TheAssassin not wanting to maintain two build systems.

**Pull request closed without merging**
