### PR TITLE
Release static binaries only

### LINKED ISSUE #1: Support building of static libraries on Alpine Linux
Cross-reference to the Alpine Linux feature report:
* https://gitlab.alpinelinux.org/alpine/aports/-/issues/15052

### PR DESCRIPTION
**Pull request by TheAssassin**
Fixes #1.

### CODE REVIEW

**Comment by TheAssassin** [comment]
@probonopd static binaries for libassuan are not available for arm, apparently, but only for x86_64/i686. Could you open another issue, please?

**Comment by probonopd** [comment]
https://gitlab.alpinelinux.org/alpine/aports/-/issues/15054

**Review by probonopd — COMMENTED** [review]
Looking good, but could we also optimize for size here, along the lines of

```
# Minimize binary size
export CFLAGS="-ffunction-sections -fdata-sections -Os"
```

for everything?

**Comment by TheAssassin** [comment]
It won't save any significant amount of space, but comes at the cost of reduced debuggability. I don't see any point in doing so. I'd rather review what we are linking against first.

By the way, I would not recommend stripping any of the binaries either.

**Comment by probonopd** [comment]
[Answer by alice](https://gitlab.alpinelinux.org/alpine/aports/-/issues/15054#note_320108) upstream regarding the missing ARM builds:

> that's because the arm builders are/were offline, but it will be there when they come back

It seems like the ARM builders have been down since ~ a week. Hopefully will be back soon.

**Comment by TheAssassin** [comment]
We have no pressure, really, do we? I don't mind keeping this open for another week. AppImageKit is still up and running, and nobody's using this repository as of yet.

**Comment by TheAssassin** [comment]
Just tried, ARM packages for libassuan-static are available now. I'll restart the CI.

**Comment by TheAssassin** [comment]
Please do not unexpectedly merge PRs. I just found a regression.

**Comment by TheAssassin** [comment]
Note: regression only affects AppImageLauncher and is likely due to the runtime itself, not appimagetool's now-static AppImage. The AppImage works fine without AppImageLauncher. I'll open an issue in the right place once I know what the problem is.

**Pull request merged**
