### PR TITLE
don't bundle broken zsyncmake

### PR DESCRIPTION
**Pull request by Samueru-sama**
lets see if we can fix this before [this fails](https://github.com/zen-browser/desktop/actions/runs/12246343549)

### CODE REVIEW

**Comment by TheAssassin** [comment]
We do not know for sure that it's broken. As said, if you extract the AppImage, the zsyncmake binary does its job just fine.

**Comment by Samueru-sama** [comment]
> We do not know for sure that it's broken. As said, if you extract the AppImage, the zsyncmake binary does its job just fine.

I'm 100% that's the problem, you can see on Brave AppImage workflow how the zsync files stopped being made after this, and it is a problem that I ran into before when I tried the standalone binary before the it was bundled.

**Comment by TheAssassin** [comment]
Merging for now until we find the bug.

**Review by TheAssassin — APPROVED** [review]

**Comment by TheAssassin** [comment]
I backed up the broken binaries in https://github.com/AppImage/appimagetool/releases/tag/broken-zsyncmake.

**Comment by Samueru-sama** [comment]
Thanks @TheAssassin but it is too late 😭

image

However it seems this didn't cause the entire Zen workflow to fail like I expected to happen, phew!

**Comment by Samueru-sama** [comment]
@TheAssassin https://github.com/Samueru-sama/SpeedCrunch-AppImage-test/releases/tag/continuous

Everything went back to normal as expected.

I tested with that other appimage because I forgot that I build rofi on Alpine, so there is no zsync in the runner to test since the alpine repos don't have it. 

Before this PR was merged: 

https://github.com/Samueru-sama/SpeedCrunch-AppImage-test/actions/runs/12247983560/job/34166786782

After the PR was merged: 

https://github.com/Samueru-sama/SpeedCrunch-AppImage-test/actions/runs/12248171013

**Pull request merged**
